
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int CR = 20;
  public static final int CLASS = 9;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int INT = 12;
  public static final int PRIVATE = 11;
  public static final int SEMI = 2;
  public static final int CRPAREN = 18;
  public static final int LPAREN = 7;
  public static final int PUBLIC = 10;
  public static final int ST = 19;
  public static final int STRING = 23;
  public static final int COMMA = 21;
  public static final int FLOAT = 13;
  public static final int PROTECTED = 16;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int CLPAREN = 17;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int STR = 15;
  public static final int DOUBLE = 14;
  public static final int UMINUS = 5;
  public static final int NAMESPACE = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "CLASS",
  "PUBLIC",
  "PRIVATE",
  "INT",
  "FLOAT",
  "DOUBLE",
  "STR",
  "PROTECTED",
  "CLPAREN",
  "CRPAREN",
  "ST",
  "CR",
  "COMMA",
  "NUMBER",
  "STRING",
  "NAMESPACE"
  };
}

